DROP TABLE IF EXISTS Artworks;
CREATE TABLE Artworks (
Id INT PRIMARY KEY IDENTITY(1,1),
Title NVARCHAR(200) NOT NULL,
Artist NVARCHAR(200),
Period NVARCHAR(100),
CreatedAt DATETIME DEFAULT GETDATE()
);
INSERT INTO Artworks (Title, Artist, Period)
VALUES ('Annunciation' , 'Leonardo Da Vinci' , 'Renaissance'),
('Doni Tondo' , 'Michelangelo Bounarotti' , 'Renaissance'),
('Assumption of Virgin' , 'Titian' , 'Rennaissance'),
('Virgin of the Rocks' , 'Leonardo da Vinci' , 'Rennaissance'),
('The Entombment of Christ' , 'Caravvagio' , 'Rennaissance'),
('Diana and Actaeon' , 'Titian' ,  'Renaissance'),
('Venus of Urbino' , 'Titian' , 'Rennaissance'),
('The Last Supper' , 'Leonardo Da Vinci' , 'Rennaissance'),
('Mona Lisa' , 'Leonardo Da Vinci' , 'Rennaissance'),
('Bacchus and Adriane' , 'Titian' , 'Rennaissance'),
('The Birth of Venus' , 'Sandro Boticelli' , 'Rennaissance'),
('The Sistine Madonna' , 'Raphael' , 'Rennaissance'),
('The School of Athens' , 'Rafaello' , 'Rennaissance'),
('The Virgin and Child with St. Anne' , 'Leonardo Da Vinci' , 'Rennaissance'),
('Arnolfini Portrait' , 'Jan Van Eyck' , 'Rennaissance'),
('The Baptism of Christ' , 'Andrea del Verocchio' , 'Rennaissance'), 
('The Garden of Earthly Delights' , 'Hieronymous Bosch' , 'Rennaissance'),
('Lady with an Ermine' , 'Leonardo Da Vinci' , 'Rennaissance'),
('Flagellation of Christ ' , 'Pierro Della Frnacesca' , 'Rennaissance'),
('Lamentation of Christ' , 'Andrea Mantegna' , 'Rennaissance'),
('Adoration of the Magi' , 'Leonardo Da Vinci' , 'Rennaisance'),
('Portrait of a Man' , 'Jan Van Eyck' , 'Rennaisance'),
('The Ambassadors' , 'Hans Holbein' , 'Rennaisance'),
('The Burial of the Count of Orgaz' , 'El Greco' , 'Rennaisance'),
('The Wedding at Canada' , 'Paolo Veronese' , 'Rennaissance'),
('The Swing' , 'John Fragonard' , 'Rococo'),
('The Earth' , 'Nicholas Lancret' , 'Rococo'),
('Princess Marie Adelaide of France', 'Jean-Marc Nattier' , 'Rococo'),
('The Crowned Amorous, or the Musical Contest' , 'Jean-Honore Fragonard' , 'Rococo'),
('The Calling of Saint Matthew' , 'Caravaggio' , 'Rococo'),
('Portrait of the Marquiese de Pompadour' , 'François Boucher' , 'Rococo') , 
('Pilgrimage to Cythera' , 'Jean-Antine Watteau' , 'Rococo'),
('The Supper at Erasmus' , 'Caravaggio' , 'Rococo'),
('Triumph of Venus' , 'François Boucher' , 'Rococo'),
('The Marriage', 'Giambattista Tiepolo', 'Rococo'),
('The Declaration of Love' , 'Jean-Fraçois de Troy' , 'Rococo'),
('Marie Antoniette in a Court Dress' , 'Elisabeth Louise Vigee-Le Brun' , 'Rococo'),
('The Settlement(Marriage A la Mode)' , 'William Hogarth' , 'Rococo'),
('The Blue Boy', 'Thomas Gainsborough', 'Rococo'),
('The Oath of the Horatii' , 'Jaques-Lois David' , 'Neoclassicism'),
('Death of Socrates' , 'Jaques-Louis David' , 'Neoclassicism'),
('La Grande Odalisque' , 'Jean-Auguste-Dominique Ingres' , 'Neoclassicism'),
('The Coronation of Napoleon' , 'Jaques-Louis David' , 'Neoclassicism'),
('The Death of General Wolfe' , 'Benjamin West' , 'Neoclassicism'),
('Self-portrait with Two Pupils' , 'Elisabeth Vigee Le Brun' , 'Neoclassicism'),
('Marie Antoniette and her Children' , 'Elisabeth Vigee Le Brun' , 'Neoclassicism'),
('Et in Arcadia Ego' , 'Jean-Baptiste-Camille Corot' , 'Neoclassicism'),
('Portrait of Sarah Harrop as a Muse' , 'Angelica Kaufmann' , 'Neoclassicism'),
('Princesse de Broglie' , 'Jean Auguste Dominique Ingres' , 'Neoclassicism'),
('The Envoys of Agamemnon' , 'Jean-Auguste-Dominique Ingres' , 'Neoclassicism'),
('Saturn Devouring His Son' , 'Francisco Goya' , 'Romanticism'),
('The Death of Sardanapalus' , 'Eugenie Delacroix' , 'Romanticism'),
('Monk by the Sea' , 'Caspar David Friedrick' , 'Romanticism'),
('The Raft of the Medusa' , 'Thedore Gericault' , 'Romanticism'),
('Calais Per' , 'Joseph Wiliam Turner' , 'Romanticism'),
('Salisbury Cathedral from the Meadows' , 'John Constable' , 'Romanticism'),
('Le Defensur' , 'Honore Daumier' , 'Realism'),
('The Potato Eathers' , 'Vincent Van Gogh' , 'Realism'),
('The Tortoise Trainer' , 'Osman Hamdi Bey' , 'Realism'),
('François Millet' , 'Woman Baking Bread' , 'Realism'),
('The Gleaners' , 'François Millet' , 'Realism'),
('A Wagon of the Third Class' , 'Honore Daumier' , 'Realism'),
('Gathering Wood' , 'Aton Mauve' , 'Realism'),
('Joan of Arc' , 'Jules Bastien-Lepage' , 'Realism'),
('Barge Haulers on the Volga' , 'Ilya Pepin' , 'Realism'),
('Ivan the Terrible and His Son Ivan' , 'Ilya Pepin' , 'Realism'),
('Impression' , 'Claude Monet' , 'Impressionism'),
('Bal du Moulin de la Galette' ,'Pierre Auguste Renoir' , 'Impressionism'),
('The Dance Class' , 'Edgar Degas' , 'Impressionism'),
('The Persistence of Memory' , 'Salvador Dali' , 'Impressionism'),
('The Son of Man' , 'Rene Margritte' , 'Impressionism'),
('The Two Fridas' , 'Frida Kahlo' , 'Impressionism'),
('The Scream' , 'Edvard Munch' , 'Expessionism'),
('Composition' , 'Vasily Kandinsky' , 'Expressionism'),
('The Kiss' , 'Gustav Klimt', 'Art Nouveau'),
('The Seasons' , 'Alphonse Mucha' , 'Art Nouveau'),
('Guernica' , 'Pablo Picasso' , 'Cubism'),
('Violin and Candlestick' , 'Georges Braque' , 'Cubism'),
('Marilyn Diptych' ,'Andy Warhol' , 'PopArt'),
('Whamm!' , 'Roy Lichtenstein' , 'PopArt');
SELECT * FROM  Artworks;
