name: .NET Build Pipeline

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet Packages
      run: nuget restore src/ConsoleApp2.csproj -PackagesDirectory src/packages

    - name: Build Project
      run: msbuild src/ConsoleApp2.csproj /p:Configuration=Release /p:RestorePackages=false
